openapi: 3.0.3
info:
  title: CryptoBot - Accounts
  description: >-
    microservicio encargado del manejo de las cuentas de clientes y
    administradores
  version: 0.1.0
paths:
  /accounts/create:
    post:
      tags:
        - account
      summary: creates client user
      description: create the user saves it on the database
      requestBody:
        description: create account
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create'
        required: true
      responses:
        '200':
          description: account created
        '208':
          description: account already exists
        '500':
          description: Internal error creating account
  /accounts/login(to_do):
    post:
      tags:
        - account
      summary: log in user on web platform
      description: the  manually enters the web platform
      requestBody:
        description: log in account
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/log_in'
        required: true
      responses:
        '200':
          description: account logged
        '208':
          description: account already on session(to_do)
        '500':
          description: Internal error log in account
  /accounts/edit:
    post:
      tags:
        - account
      summary: edits client user properties using the telegram_id
      description: updates the user account in the database
      requestBody:
        description: edit user account
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/edit'
        required: true
      responses:
        '200':
          description: account edited
        '500':
          description: Internal error editing account
  /accounts/change-password:
    post:
      tags:
        - account
      summary: change password using account email
      description: updates the user account in the database
      requestBody:
        description: edits  account password
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/password'
        required: true
      responses:
        '200':
          description: password changed
        '500':
          description: Internal error editing account
  /accounts/delete/:telegram_id:
    delete:
      tags:
        - account
      summary: deletes client user properties using the telegram_id
      description: deletes the user account in the database with the telegram_id
      responses:
        '200':
          description: account deleted
        '500':
          description: Internal error editing account
components:
  schemas:
    edit:
      type: object
      properties:
        telegram_id:
          type: integer
          example: '123'
        first_name:
          type: string
          example: juan
        last_name:
          type: string
          example: cardenas
        email:
          type: string
          example: juan@example.com
        username:
          type: string
          example: sagarus
    create:
      type: object
      properties:
        telegram_id:
          type: integer
          example: '123'
        first_name:
          type: string
          example: juan
        last_name:
          type: string
          example: cardenas
        username:
          type: string
          example: sagarus
        rol:
          type: string
          example: cliente
    password:
      type: object
      properties:
        telegram_id:
          type: integer
          example: '123'
        password:
          type: string
          example: cerradura
    log_in:
      type: object
      properties:
        username:
          type: string
          example: sagarus
        password:
          type: string
          example: cerradura
